# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4df16217cc6fa1e90dd2e309411183ff8b6df75fb7e5a67f73320d9f08dfde78cbc3be014202d994fb8fb30a713ccc7d0fb87de19df15dbfd7e51807f97d6225

test:
  secret_key_base: b28cae9353a1cac6b70d9e086183bef12cf71e5c4aa879289f832b2e0e671ddbf13332b561c556cc7312ec37121a6f9936c1c04f18487e32b2c2949f806e059b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
